name: Orvyn CI/CD Web Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Codes
        uses: actions/checkout@v4

      - name: Setup NodeJS Runtime Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Type Checks
        run: npm run check-types

      - name: Build Next.js Portal Frontend
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: https://ypmzmdiehqycwmucmslj.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: sb_publishable_placeholder
